apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-gen-app
  namespace: demo
  labels:
    app: image-gen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-gen-app
  template:
    metadata:
      labels:
        app: image-gen-app
    spec:
      containers:
        - name: image-gen-app
          image: inglebard/retroarch-web:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: image-gen-app-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: image-gen-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
