---
apiVersion: v1
kind: Service
metadata:
  name: image-gen-app-service
spec:
  type: NodePort
  selector:
    app: image-gen-app
  ports:
    - protocol: TCP
      port: 80       # Service Port
      targetPort: 80 # Container Port
      nodePort: 30011 # NodePort
