name: CD - Deploy to Kind & ArgoCD

on:
  workflow_run:
    workflows: ["Java CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create Kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: demo

      - name: Deploy with Helm
        run: |
          helm upgrade --install myapp ./helm/myapp \
            --set image.repository=myuser/myapp \
            --set image.tag=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Wait for pod & fetch logs
        run: |
          kubectl rollout status deployment/myapp
          kubectl logs deployment/myapp > deployment_logs.txt

      - name: Helm Lint
        run: helm lint ./helm/myapp

      - name: Push Helm chart to ChartMuseum
        run: |
          helm package ./helm/myapp
          curl --data-binary "@myapp-0.1.0.tgz" http://localhost:8080/api/charts

      - name: ArgoCD AppSet Apply
        run: |
          kubectl apply -f appset.yaml
