# .github/workflows/common.yaml
name: Common Workflow - CI-CD

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Start Common Workflow
        run: echo "Common workflow triggered."