name: Helm Nginx Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Nginx Image
        run: |
          docker pull nginx:latest
          docker save nginx:latest -o nginx.tar

      - name: Scan Nginx Image with Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy image -f json -o trivy.json nginx:latest

      - name: Generate Trivy HTML Report
        run: |
          python3 scripts/trivy_to_html.py
        env:
          TRIVY_JSON: trivy.json
          REPORT_HTML: trivy_report.html

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy_report.html

      - name: Lint Helm Chart
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm lint ./helm/hello-world

      - name: Validate and Package Helm Chart
        id: package_helm
        run: |
            helm template ./helm/hello-world
            helm package ./helm/hello-world --version "0.1.${{ github.run_number }}"
            ls -1 *.tgz | sed -n 's/\.tgz$//p' > chart_version.txt
    
      - name: Set Up Local K3s Cluster
        run: |
            curl -sfL https://get.k3s.io | sh -
            echo "Waiting for K3s to be ready..."
            for i in {1..30}; do
              if kubectl get nodes &>/dev/null; then
                echo "K3s is ready."
                break
              fi
              echo "Waiting for K3s to initialize... ($i/30)"
              sleep 10
            done
            kubectl create namespace test
            CHART_VERSION=$(cat chart_version.txt)
            helm install hello-world "./0.1.${{ github.run_number }}.tgz" --namespace test

      - name: Create Release Tag
        id: create_tag
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a v$VERSION -m "Release v$VERSION"
          git push origin v$VERSION
          echo "tag=$VERSION" >> $GITHUB_ENV

      - name: Generate HTML Report for Steps
        run: |
          python3 scripts/pipeline_to_html.py
        env:
          STATUS_FILE: status.json
          HTML_REPORT: pipeline_report.html

      - name: Upload Pipeline Report
        uses: actions/upload-artifact@v3
        with:
          name: pipeline-report
          path: pipeline_report.html
